# Generated by Django 4.2 on 2024-01-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phones',
            field=models.CharField(max_length=50),
        ),
    ]
